use std::marker::PhantomData;
use serde::{Serialize, Deserialize};
use garbled_snark_verifier::bag::S;
use crate::babe::h;

pub type SolderedWire = ([u8; 16], [u8; 16]);
pub type InstancesWires = Vec<SolderedWire>;
pub type Sha256Commit = [u8; 32];

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct SolderedWiresInput(pub Vec<InstancesWires>);

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct SolderedLabelsData {
    pub deltas: Vec<Vec<([u8; 16], [u8; 16])>>,
    pub base_commitment: Vec<(Sha256Commit, Sha256Commit)>,
    pub commitments: Vec<Vec<(Sha256Commit, Sha256Commit)>>,
}

/// This struct represents for the STARK Proof generated by Verifier during soldering.
/// In production, this is replaced by the actual proof generated by Ziren.
pub struct SolderingProof {
    // public input of the proof
    pub soldered_labels_data: SolderedLabelsData,
    pub _proof: PhantomData<()>
}

// Offchain data that Verifier sends to Prover after Soldering.
pub struct SolderingData {
    pub finalized_indices: Vec<usize>,
    pub soldering_proof: SolderingProof,
    /// [0-label of wire-0 (constant false), 1-label of wire-1 (constant true)].
    pub constant_labels: Vec<[S; 2]>,
}


/// Called by the zkVM guest.
pub fn soldering_guest_compute(input: &SolderedWiresInput) -> SolderedLabelsData {
    let instances = &input.0;
    assert!(!instances.is_empty(), "at least one instance required");

    let base = &instances[0];

    let base_commitment = base
        .iter()
        .map(|(l0, l1)| (h(l0), h(l1)))
        .collect();

    let mut deltas = Vec::with_capacity(instances.len() - 1);
    let mut commitments = Vec::with_capacity(instances.len() - 1);

    let delta = |a: &[u8; 16], b: &[u8; 16]| -> [u8; 16] {
        let mut res = [0u8; 16];
        for i in 0..16 {
            res[i] = a[i] ^ b[i];
        }
        res
    };

    for inst in instances[1..].iter() {
        deltas.push(
            inst.iter()
                .zip(base.iter())
                .map(|((li0, li1), (b0, b1))| {
                    (delta(li0, b0), delta(li1, b1))
                })
                .collect(),
        );
        commitments.push(
            inst.iter()
                .map(|(l0, l1)| (h(l0), h(l1)))
                .collect(),
        );
    }

    SolderedLabelsData { base_commitment, deltas, commitments }
}


/// Build `SolderedWiresInput` from the verifier's finalized instances.
/// `instances[0]` = base (finalized_indices[0]), `instances[1..]` = non-base in order.
#[cfg(feature = "garbled")]
pub fn build_soldered_wires_input(
    verifier: &crate::verifier::BABEVerifier,
    finalized_indices: &[usize],
) -> SolderedWiresInput {
    SolderedWiresInput(
        finalized_indices
            .iter()
            .map(|&idx| {
                let inst = &verifier.instances[idx];
                let delta = inst.secrets.delta;
                inst.secrets
                    .encoding_keys
                    .iter()
                    .map(|&ek| (ek.0, (ek ^ delta).0))
                    .collect()
            })
            .collect(),
    )
}

/// Verify that the guest output's commitments match the `CACSetupPackage`.
#[cfg(feature = "garbled")]
pub fn verify_soldering_output(
    output: &SolderedLabelsData,
    package: &crate::cac::CACSetupPackage,
    finalized_indices: &[usize],
) -> Result<(), String> {
    let base_idx = finalized_indices[0];
    for (j, (h0, h1)) in output.base_commitment.iter().enumerate() {
        let committed = &package.commits[base_idx].input_commits[j];
        if h0 != &committed[0] {
            return Err(format!("base commitment mismatch at wire {j} label 0"));
        }
        if h1 != &committed[1] {
            return Err(format!("base commitment mismatch at wire {j} label 1"));
        }
    }
    for (i, &idx) in finalized_indices[1..].iter().enumerate() {
        for (j, (h0, h1)) in output.commitments[i].iter().enumerate() {
            let committed = &package.commits[idx].input_commits[j];
            if h0 != &committed[0] {
                return Err(format!("instance {idx} commitment mismatch at wire {j} label 0"));
            }
            if h1 != &committed[1] {
                return Err(format!("instance {idx} commitment mismatch at wire {j} label 1"));
            }
        }
    }
    Ok(())
}
