use std::marker::PhantomData;
use serde::{Serialize, Deserialize};
use crate::utils::h_256;

pub type SolderedWire = ([u8; 16], [u8; 16]);
pub type InstancesWires = Vec<SolderedWire>;
pub type Sha256Commit = [u8; 32];

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct SolderedWiresInput(pub Vec<InstancesWires>);

#[derive(Serialize, Deserialize, Debug, PartialEq)]
pub struct SolderedLabelsData {
    pub deltas: Vec<Vec<([u8; 16], [u8; 16])>>,
    pub base_commitment: Vec<(Sha256Commit, Sha256Commit)>,
    pub commitments: Vec<Vec<(Sha256Commit, Sha256Commit)>>,
}

/// This struct represents for the STARK Proof generated by Verifier during soldering.
/// In production, this is replaced by the actual proof generated by Ziren.
pub struct SolderingProof {
    // public input of the proof
    pub soldered_output: SolderedLabelsData,
    pub _proof: PhantomData<()>
}

// Offchain data that Verifier sends to Prover after Soldering.
pub struct SolderingData {
    pub finalized_indices: Vec<usize>,
    pub soldering_proof: SolderingProof,
}


/// Called by the zkVM guest.
pub fn soldering_guest_compute(input: &SolderedWiresInput) -> SolderedLabelsData {
    let instances = &input.0;
    assert!(!instances.is_empty(), "at least one instance required");

    let base = &instances[0];

    let base_commitment = base
        .iter()
        .map(|(l0, l1)| (h_256(l0), h_256(l1)))
        .collect();

    let mut deltas = Vec::with_capacity(instances.len() - 1);
    let mut commitments = Vec::with_capacity(instances.len() - 1);

    let delta = |a: &[u8; 16], b: &[u8; 16]| -> [u8; 16] {
        let mut res = [0u8; 16];
        for i in 0..16 {
            res[i] = a[i] ^ b[i];
        }
        res
    };

    for inst in instances[1..].iter() {
        deltas.push(
            inst.iter()
                .zip(base.iter())
                .map(|((li0, li1), (b0, b1))| {
                    (delta(li0, b0), delta(li1, b1))
                })
                .collect(),
        );
        commitments.push(
            inst.iter()
                .map(|(l0, l1)| (h_256(l0), h_256(l1)))
                .collect(),
        );
    }

    SolderedLabelsData { base_commitment, deltas, commitments }
}


#[cfg(not(target_os = "zkvm"))]
/// Build `SolderedWiresInput` from the verifier's finalized instances.
/// `instances[0]` = base (finalized_indices[0]), `instances[1..]` = non-base in order.
pub fn build_soldered_wires_input(
    verifier: &crate::verifier::BABEVerifier,
    finalized_indices: &[usize],
) -> SolderedWiresInput {
    SolderedWiresInput(
        finalized_indices
            .iter()
            .map(|&idx| {
                let ls = &verifier.light_secrets[idx];
                let delta = &ls.delta;
                let encoding_keys = &ls.encoding_keys;

                (0..2)
                    .flat_map(|i| {
                        encoding_keys[i]
                            .iter()
                            .map(move |&ek| (ek.0, (ek ^ delta[i]).0))
                    })
                    .collect::<Vec<_>>()
            })
            .collect(),
    )
}

