[package]
name = "aes-host"
version.workspace = true
edition.workspace = true

[dependencies]
zkm-sdk = { workspace = true }
garbled-snark-verifier = { workspace = true }
verifiable-circuit-babe = { workspace = true }
aes = "0.8"
ark-bn254 = { version = "0.5.0", features = ["curve", "scalar_field"], default-features = false }

[build-dependencies]
zkm-build = { workspace = true }