[package]
name = "aes-guest"
version.workspace = true
edition.workspace = true

[dependencies]
zkm-zkvm = { workspace = true, features = ["embedded"] }
garbled-snark-verifier = { workspace = true }
verifiable-circuit-babe = { workspace = true }
ark-bn254 = { version = "0.5.0", features = ["curve", "scalar_field"], default-features = false }
